kind: Service
apiVersion: v1
metadata:
  name: vibot-voice
spec:
  selector:
    app: vibot-voice
  ports:
    - port: 10000
      targetPort: 8080
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibot-voice
spec:
  selector:
    matchLabels:
      app: vibot-voice
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vibot-voice
    spec:
      containers:
        - name: vibot-voice
          image: jllado-server:5000/vibot/vibot-voice:latest
          imagePullPolicy: Always

